core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.image,name="image-test"),
    path('<str:dept>/',views.jsonitems,name="core-info")
]

events/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.views.generic import TemplateView

app_name = "events"

urlpatterns = [
    path('<str:event>/', views.Renderform.as_view(),name="form-view"),
]

main/urls.py
from django.urls import path,include
from . import views
from django.views.generic import TemplateView

app_name='main'

urlpatterns = [
    path('',views.home,name='landing-page'),
    path('depts/<str:dept>',views.islandview,name='island-view'),
]

sattva/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('',include('main.urls')),
    path('admin/admin', admin.site.urls),
    path('core/',include('core.urls')),
    path('events/',include('events.urls'))
]

events/views.py
from django.shortcuts import render,redirect
from .forms import *
from django.core.mail import send_mail,EmailMessage
from django.views.generic import TemplateView
from sattva.settings import EMAIL_HOST_USER
from django.urls import reverse
from django.conf.urls import static
from .models import Event

# Create your views here.
class Renderform(TemplateView):
    def get(self,request,event):
        
        dict_event = {'solosinging':SoloSingingForm(),'rapbattle':RapBattleForm(),'groupsinging':GroupSingingForm(),'shortfilms':ShortFilmsForm(),'poetry':PoetryForm(),'groupsinging':GroupSingingForm(),'beatboxing':BeatBoxingForm(),'classicaldance':ClassicalDanceForm(),'westerndance':WesternDanceForm(),'monoact':MonoActForm()}
        dict_event.update({'advision':AdVisionForm(),"turnaround":TurnaroundForm(),"houseofbattle":HouseOfBattleForm(),"tazhakhabar":TazhaKhabarForm(),"bidweiser":BidweiserForm(),"marketguru":MarketGuruForm()})
        dict_event.update({'standupworkshop':StandUpWorkshopForm(),'influentialtrends':InfluentialTrendsWorkshopForm(),'danceworkshop':DanceWorkshopForm(),'fitnessworkshop':FitnessWorkshopForm(),'actingworkshop':ActingWorkshopForm()})
        dict_event.update({"fifa":FifaForm(),'rocketleague':RocketLeagueForm(),'pubg':PUBGForm()})
        dict_event.update({'popculture':PopCultureForm(),'punintended':PunIntendedForm(),'mrmssattva':MrMsSattvaForm()})
        dict_event.update({'photographycontests':PhotographyContestForm(),'photographyworkshops':PhotographyWorkshopForm()})
        dict_event.update({'charadeswithatwist':CharadesForm(),'glamup':GlamUpForm()})
        form = dict_event[event]
        if 'photography' in event:
            eventModel = Event.objects.all().filter(eventslug__icontains=event).first()
            if 'contest' in event:
                contests_rules = eventModel.rules.split('|')
                for i in range(len(contests_rules)):
                    contests_rules[i] = contests_rules[i].split(':')
                    contests_rules[i][1] = contests_rules[i][1].split('##')
                contests_details = eventModel.desc.split('|')
                for i in range(len(contests_details)):
                    contests_details[i] = contests_details[i].split(':')
                return render(request,'events/eventform.html',{'form':form,'event':eventModel,'rules':contests_rules,'desc':contests_details})
            else:
                workshops_details = eventModel.desc.split('|')
                for i in range(len(workshops_details)):
                    workshops_details[i] = workshops_details[i].split(':')
        eventModel = Event.objects.all().filter(eventslug__icontains=event).first()
        return render(request,'events/eventform.html',{'form':form,'event':eventModel,'rules':eventModel.rules.split('.')[:-1]})
        
            # return render(request,'events/sorry.html',{})

        # return render(request,'events/eventform.html',{'form':form,'rules':eventModel.rules.split('.'),'desc':eventModel.desc,'script':eventModel.url})
    def post(self,request,event):
        dict_event = {'solosinging':SoloSingingForm(request.POST),'shortfilms':ShortFilmsForm(request.POST),'poetry':PoetryForm(request.POST),'groupsinging':GroupSingingForm(request.POST),'beatboxing':BeatBoxingForm(request.POST),'classicaldance':ClassicalDanceForm(request.POST),'westerndance':WesternDanceForm(request.POST),'monoact':MonoActForm(request.POST)}
        dict_event.update({'advision':AdVisionForm(request.POST),"turnaround":TurnaroundForm(request.POST),"houseofbattle":HouseOfBattleForm(request.POST),"tazhakhabar":TazhaKhabarForm(request.POST),"bidweiser":BidweiserForm(request.POST),"marketguru":MarketGuruForm(request.POST)})
        dict_event.update({'standupworkshop':StandUpWorkshopForm(request.POST),'influentialtrends':InfluentialTrendsWorkshopForm(request.POST),'danceworkshop':DanceWorkshopForm(request.POST),'fitnessworkshop':FitnessWorkshopForm(request.POST),'actingworkshop':ActingWorkshopForm(request.POST)})
        dict_event.update({"fifa":FifaForm(request.POST),'rocketleague':RocketLeagueForm(request.POST),'pubg':PUBGForm(request.POST)})
        dict_event.update({'popculture':PopCultureForm(request.POST),'punintended':PunIntendedForm(request.POST),'mrmssattva':MrMsSattvaForm(request.POST)})
        dict_event.update({'photographycontests':PhotographyContestForm(request.POST),'photographyworkshops':PhotographyWorkshopForm(request.POST)})
        form = dict_event[event]
        if form.is_valid() == True:
            if 'email' in form.fields:
                recepient = str(form['email'].value())
                mail_content = f"""<!DOCTYPE html>
                <html lang="en">

                <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <style>
                    @import url("https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap%22);
                </style>
                <title>Document</title>
                </head>

                <body style="

                width: 700px;
                margin: 0 auto;
                overflow-y: scroll;
                overflow-x: hidden;
                font-family: ' Work Sans', Arial, sans-serif; position: relative;
                margin-bottom: 30px;">
                <header style="  text-align: center;  margin: 50px auto 30px;">
                    <h1 style="display: inline-block;">Sattva'<small style="font-size: 0.7em;">21</small></h1>
                </header>

                <main>
                    <div class="homeSlide" style="background: #ffd3e0 !important;
                    width: 100%;
                    height: auto;
                    padding: 30px;
                    border-radius: 20px;
                    padding-bottom: 70px;">

                    <div class="image" style="width: 420px;
                    height: 400px;
                    margin: 0 auto;">
                        <img src="https://i.imgur.com/5zDItAW.png" alt="" style="width: 90%;">
                    </div>


                    <h1 style="text-align: center;">Hi {request.POST.get('name')},
                        <br>
                        Welcome To XYZ Event
                    </h1>
                    <br>
                    <p style="text-align: center;
                    font-size: 1.5em;">Thanks For Registering</p>
                    </div>
                </main>
                </body>
                </html>"""
                msg = EmailMessage('Hi brotheriinoo',mail_content, EMAIL_HOST_USER, [recepient])
                msg.content_subtype = "html"
                html_content = '<p>This is an <strong>important</strong> message.</p>'
                msg.send()
                # subject = 'hi deer'
                # message = 'Hope you are enjoying your Django Tutorials'
                # send_mail(subject, message, EMAIL_HOST_USER, [recepient], fail_silently = False)
                return render(request,'events/success.html',{'recepient':recepient})
        return render(request,'events/eventform.html',{'form':form,'notvalid':'notvalid'})

events/templates/events/eventform.html
{% extends 'main/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Registration{% endblock %}
{% block content %}


<div class="ui modal" id="eventpopup">
    <i class="close icon" style="z-index: 3000000;"><a href="{% url 'main:island-view' event.deptName|lower %}"></a></i>
    <div class="tabmenu eventpopup fadeIn animated2s">
        <div class="ui top attached tabular menu">
            <a class="item trans" data-tab="details">Details</a>
            <a class="item trans active" data-tab="register">Register</a>
        </div>
        <div class="ui bottom attached tab segment animated4s fadeIn details-container" data-tab="details">
            {% if 'photography' in event.eventslug %}
            {% for contest,detail in desc %}
            <h1>{{contest}} Details</h1>
            <p>{{detail}}</p>
            {% endfor %}
            {% else %}
            <h1>Details</h1>
            <iframe  src="{{event.youtube}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <br>
            <br>

            <p>{{event.desc}}</p>
            
            {% endif %}
        </div>
        <div class="ui bottom attached tab segment active animated4s fadeIn" data-tab="register">
            <div class="form-container">
                <div class="form-content">
                    {% if 'photography' in event.eventslug %}
                    {% for name,rule in rules %}
                        <h1>{{name}} Rules</h1>
                        <ul>
                            <li>
                                <p>Be sure to maintain decorum.</p>
                            </li>
                            <br>
                            <li>
                                <p>Avoid vulgar language and cussing.</p>
                            </li>
                            <br>
                            {% for each in rule %}
                            <li>
                                <p>{{each}}</p>
                            </li>
                            <br>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                    {% else %}
                        <h1>Rules</h1>
                        <ul>
                            {% for rule in rules %}
                            <li>
                                <p>{{rule}}</p>
                            </li>
                            <br>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="eventform">
                    <form name="submit-to-google-sheet" method="POST" id="test-form">
                        {% csrf_token %}
                        {{form|crispy}}
                        <button id="submit-form" onclick="submittosheet()" name="submitted"
                            type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>

    </div>
    <video class="scrollvideo" id="scrollvid6" autoplay>
        <source src="{% static 'videos/scroll.mp4' %}" type="video/mp4">
        Your browser does not support the video tag.
    </video>
</div>

<!--<div style="padding:10px;" class="container">
    <form name="submit-to-google-sheet" method="POST" id="test-form">
        {% csrf_token %}
        {{form|crispy}}
        <button id="submit-form" onclick="submittosheet()" class="btn btn-primary" name="submitted" type="submit">Submit</button>
    </form>
    {% for rule in rules %}
        <li>
            {{rule}}
        </li>
        {% endfor %}
        {{event.desc}}
</div>-->
{{request23}}
{% if notvalid %}
{{notvalid}}
{% else %}
{% endif %}
{% endblock %}
{% block js %}

 $(document).ready(function(){
     function eventpopup() {
        $('#eventpopup')
            .modal('show')
        ;
        var vid = document.getElementById("scrollvid9");
        vid.currentTime = 4;
    }

    eventpopup();
 });
function submittosheet()
{
const scriptURL = '{{event.url}}';
const form = document.forms['submit-to-google-sheet'];

form.addEventListener('submit', e => {
fetch(scriptURL, { method: 'POST', body: new FormData(form)})
.then(response => console.log('Success!', response))
.catch(error => console.error('Error!', error.message))
});
}
{% endblock %}

events/templates/events/sorry.html
{% extends 'main/base.html' %}
{% block content %}
<h1>Sorry form does not exist</h1>
{% endblock %}

events/templates/events/success.html
{% extends 'core/base.html' %}
{% block content %}
Email sent to {{recepient}}!!
{% endblock %}