core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.image,name="image-test"),
    path('<str:dept>/',views.jsonitems,name="core-info")
]

events/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.views.generic import TemplateView

app_name = "events"

urlpatterns = [
    path('<str:event>/', views.Renderform.as_view(),name="form-view"),
]

main/urls.py
from django.urls import path,include
from . import views
from django.views.generic import TemplateView

app_name='main'

urlpatterns = [
    path('',views.home,name='landing-page'),
    path('depts/<str:dept>',views.islandview,name='island-view'),
]

sattva/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('',include('main.urls')),
    path('admin/admin', admin.site.urls),
    path('core/',include('core.urls')),
    path('events/',include('events.urls'))
]

main/models.py
from django.db import models

# Create your models here.

class DepartmentEventIsland(models.Model):
    eventName = models.CharField(max_length=200,blank=True)
    deptslug = models.CharField(max_length=200,blank=True)
    deptid = models.CharField(max_length=200,blank=True)
    eventslug = models.CharField(max_length=200,blank=True)
    def __str__(self):
        return f"{self.eventName} - {self.deptslug} ({self.deptid}) {self.eventslug}"

main/views.py
from django.shortcuts import render
from core.models import Member
from .models import DepartmentEventIsland
from events.models import Event
# Create your views here.



def home(request):
    depts = [i['deptName'] for i in Member.objects.values('deptName').order_by('deptName').distinct()]
    depts.remove('Super Core')
    supercoredept = 'Super Core'
    return render(request,'main/index.html',{'depts':depts,'supercoredept':supercoredept,'singq':"'"})

def islandview(request,dept):
    dept = dept.title()
    dictnum = {'one':1,'two':2,'three':3,'four':4,'five':5,'six':6,'seven':7,'eight':8}
    events = DepartmentEventIsland.objects.all().filter(deptslug__icontains=dept)
    eventsfull = Event.objects.all().filter(deptName__icontains=dept).first()
    argument = dictnum[events[0].deptid]
    return render(request,'main/island.html',{'dept':dept,'argument':argument,'deptdeets':events[0],'events':events, 'deptName':eventsfull.deptName})

main/templates/main/island.html
{% extends 'main/base.html' %}
{% load static %}


{% block style %}
    
{% endblock %}

{% block js %}
    $(document).ready (function() {
        var outerContent = $('body');
        outerContent.scrollLeft($(window).width() / 5);
    });
{% endblock %}


{% block content %}
    <div onload="viewevents({{argument}})" class="map" id="bgMap" style="margin-top: -50px;z-index:6;">
        <script src="{% static 'js/islandsView.js' %}"></script>
        {% with 'images/islands/withflag/'|add:dept|add:'.png' as island_url %}
        <img src="{% static island_url %}" id="bgIsland">
        <script>
            $(document).ready ( function() {
                var isl = {
                  'PA': 85,
                  'Management': 95,
                  'Informals': 82,
                  'Workshops': 80,
                  'Photography': 57,
                  'Sports': 150
                };
              if ( $(window).width() < '600' ) {
                document.getElementById("bgIsland").style.width = isl['{{deptName}}']+'%';
                }
            });
        </script>
        {% endwith %}
        <div id="{{deptdeets.deptid}}events"  style="display:block;" class="events">
            {% for event in events %}
                <p id="{{deptdeets.deptid}}event{{forloop.counter}}">
                    {% if '{{event.eventslug}}' != '' %}
                    <a href="{% url 'events:form-view' event.eventslug %}">{{event.eventName}}</a>
                    {% else %}
                    {% endif %}
                </p>
            {% endfor %}
        </div>
        <div id="islandname"><p><a style="color: #fff!important;" id="islandDept">{{ deptName }}</a></p></div>
        <script>
            if(document.getElementById('islandDept').innerHTML == 'PA') {
                document.getElementById('islandDept').innerHTML = 'Performing Arts';
            }
        </script>
    </div>
{% endblock %}